drop old explicit template declarations
clang 19 breaks here stating:

> error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]

These explicit template declarations predate 2010 and were likely not
required in ages.